/*
 RequireJS 0.15.0 Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS i18n Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS text Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS order Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.4
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Thu Nov 11 19:04:53 2010 -0500
*/
var require,define;
(function(){function T(j){return Da.call(j)==="[object Function]"}function H(j,k,s){var q=x.plugins.defined[j];if(q)q[s.name].apply(null,s.args);else{q=x.plugins.waiting[j]||(x.plugins.waiting[j]=[]);q.push(s);y(["require/"+j],k.contextName)}}function la(j,k){Ea.apply(y,j);k.loaded[j[0]]=true}function M(j,k,s){var q,u,C;for(q=0;C=k[q];q++){C=typeof C==="string"?{name:C}:C;u=C.location;if(s&&(!u||u.indexOf("/")!==0&&u.indexOf(":")===-1))C.location=s+"/"+(C.location||C.name);C.location=C.location||
C.name;C.lib=C.lib||"lib";C.main=C.main||"main";j[C.name]=C}}function B(j){var k=true,s=j.config.priorityWait,q,u;if(s){for(u=0;q=s[u];u++)if(!j.loaded[q]){k=false;break}k&&delete j.config.priorityWait}return k}function D(j){var k,s=x.paused;if(j.scriptCount<=0){for(j.scriptCount=0;wa.length;){k=wa.shift();k[0]===null?y.onError(new Error("Mismatched anonymous require.def modules")):la(k,j)}if(!(j.config.priorityWait&&!B(j))){if(s.length){x.paused=[];for(j=0;k=s[j];j++)y.checkDeps.apply(y,k)}Fa?setTimeout(function(){y.checkLoaded(x.ctxName)},
30):y.checkLoaded(x.ctxName)}}}function S(j,k){var s=x.plugins.callbacks[j]=[];x.plugins[j]=function(){for(var q=0,u;u=s[q];q++)if(u.apply(null,arguments)===true&&k)return true;return false}}function J(j,k){if(!j.jQuery)if((k=k||(typeof jQuery!=="undefined"?jQuery:null))&&"readyWait"in k){j.jQuery=k;if(!j.defined.jquery&&!j.jQueryDef)j.defined.jquery=k;if(j.scriptCount){k.readyWait+=1;j.jQueryIncremented=true}}}function P(j){return function(k){j.exports=k}}function ca(j,k,s){return function(){var q=
[].concat(Ga.call(arguments,0));q.push(k,s);return(j?require[j]:require).apply(null,q)}}function da(j,k){var s=j.contextName,q=ca(null,s,k);y.mixin(q,{modify:ca("modify",s,k),def:ca("def",s,k),get:ca("get",s,k),nameToUrl:ca("nameToUrl",s,k),toUrl:ca("toUrl",s,k),ready:y.ready,context:j,config:j.config,isBrowser:x.isBrowser});return q}var V={},x,W,Y=[],ja,ma,va,z,c,xa,na={},Ha,Ia=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,Oa=/require\(["']([\w\!\-_\.\/]+)["']\)/g,Ea,sa=!!(typeof window!=="undefined"&&navigator&&
document),Fa=!sa&&typeof importScripts!=="undefined",Pa=sa&&navigator.platform==="PLAYSTATION 3"?/^complete$/:/^(complete|loaded)$/,Da=Object.prototype.toString,ya=Array.prototype,Ga=ya.slice,Ja,y,Aa,wa=[],Ka=false,Ba;if(typeof require!=="undefined")if(T(require))return;else na=require;y=require=function(j,k,s,q,u){var C;if(typeof j==="string"&&!T(k))return require.get(j,k,s,q);if(!require.isArray(j)){C=j;if(require.isArray(k)){j=k;k=s;s=q;q=u}else j=[]}Ea(null,j,k,C,s,q);(j=x.contexts[s||C&&C.context||
x.ctxName])&&j.scriptCount===0&&D(j)};y.onError=function(j){throw j;};define=y.def=function(j,k,s,q){var u,C,F=Ba;if(typeof j!=="string"){q=s;s=k;k=j;j=null}if(!y.isArray(k)){q=s;s=k;k=[]}if(!j&&!k.length&&y.isFunction(s)){s.toString().replace(Ia,"").replace(Oa,function(K,aa){k.push(aa)});k=["require","exports","module"].concat(k)}if(!j&&Ka){u=document.getElementsByTagName("script");for(j=u.length-1;j>-1&&(C=u[j]);j--)if(C.readyState==="interactive"){F=C;break}F||y.onError(new Error("ERROR: No matching script interactive for "+
s));j=F.getAttribute("data-requiremodule")}if(typeof j==="string")x.contexts[x.ctxName].jQueryDef=j==="jquery";wa.push([j,k,s,null,q])};Ea=function(j,k,s,q,u,C){var F,K,aa,ba,U;u=u?u:q&&q.context?q.context:x.ctxName;F=x.contexts[u];if(j){K=j.indexOf("!");if(K!==-1){aa=j.substring(0,K);j=j.substring(K+1,j.length)}else aa=F.defPlugin[j];K=F.waiting[j];if(F&&(F.defined[j]||K&&K!==ya[j]))return}if(u!==x.ctxName){K=x.contexts[x.ctxName]&&x.contexts[x.ctxName].loaded;ba=true;if(K)for(U in K)if(!(U in V))if(!K[U]){ba=
false;break}if(ba)x.ctxName=u}if(!F){F={contextName:u,config:{waitSeconds:7,baseUrl:x.baseUrl||"./",paths:{},packages:{}},waiting:[],specified:{require:true,exports:true,module:true},loaded:{},scriptCount:0,urlFetched:{},defPlugin:{},defined:{},modifiers:{}};x.plugins.newContext&&x.plugins.newContext(F);F=x.contexts[u]=F}if(q){if(q.baseUrl)if(q.baseUrl.charAt(q.baseUrl.length-1)!=="/")q.baseUrl+="/";ba=F.config.paths;K=F.config.packages;y.mixin(F.config,q,true);if(q.paths){for(U in q.paths)U in V||
(ba[U]=q.paths[U]);F.config.paths=ba}if((ba=q.packagePaths)||q.packages){if(ba)for(U in ba)U in V||M(K,ba[U],U);q.packages&&M(K,q.packages);F.config.packages=K}if(q.priority){y(q.priority);F.config.priorityWait=q.priority}if(q.deps||q.callback)y(q.deps||[],q.callback);q.ready&&y.ready(q.ready);if(!k)return}if(k){U=k;k=[];for(q=0;q<U.length;q++)k[q]=y.splitPrefix(U[q],j||C,F)}C=F.waiting.push({name:j,deps:k,callback:s});if(j){F.waiting[j]=C-1;F.specified[j]=true;if(C=F.modifiers[j]){y(C,u);if(C=C.__deferMods)for(q=
0;q<C.length;q++){U=C[q];K=U[U.length-1];if(K===undefined)U[U.length-1]=u;else typeof K==="string"&&C.push(u);require.def.apply(require,U)}}}if(j&&s&&!y.isFunction(s))F.defined[j]=s;aa&&H(aa,F,{name:"require",args:[j,k,s,F]});x.paused.push([aa,j,k,F]);if(j){F.loaded[j]=true;F.jQueryDef=j==="jquery"}};y.mixin=function(j,k,s){for(var q in k)if(!(q in V)&&(!(q in j)||s))j[q]=k[q];return y};y.version="0.15.0";x=y.s={ctxName:"_",contexts:{},paused:[],plugins:{defined:{},callbacks:{},waiting:{}},skipAsync:{},
isBrowser:sa,isPageLoaded:!sa,readyCalls:[],doc:sa?document:null};y.isBrowser=x.isBrowser;if(sa){x.head=document.getElementsByTagName("head")[0];if(Aa=document.getElementsByTagName("base")[0])x.head=Aa.parentNode}y.plugin=function(j){var k,s,q,u=j.prefix,C=x.plugins.callbacks,F=x.plugins.waiting[u],K;k=x.plugins.defined;q=x.contexts;if(k[u])return y;k[u]=j;K=["newContext","isWaiting","orderDeps"];for(k=0;s=K[k];k++){x.plugins[s]||S(s,s==="isWaiting");C[s].push(j[s])}if(j.newContext)for(s in q)if(!(s in
V)){k=q[s];j.newContext(k)}if(F){for(k=0;q=F[k];k++)j[q.name]&&j[q.name].apply(null,q.args);delete x.plugins.waiting[u]}return y};y.completeLoad=function(j,k){for(var s;wa.length;){s=wa.shift();if(s[0]===null){s[0]=j;break}else if(s[0]===j)break;else la(s,k)}s&&la(s,k);k.loaded[j]=true;J(k);k.scriptCount-=1;D(k)};y.pause=y.resume=function(){};y.checkDeps=function(j,k,s,q){if(j)H(j,q,{name:"checkDeps",args:[k,s,q]});else for(j=0;k=s[j];j++)if(!q.specified[k.fullName]){q.specified[k.fullName]=true;
q.startTime=(new Date).getTime();k.prefix?H(k.prefix,q,{name:"load",args:[k.name,q.contextName]}):y.load(k.name,q.contextName)}};y.modify=function(j,k,s,q,u){var C,F,K=(typeof j==="string"?u:k)||x.ctxName,aa=x.contexts[K],ba=aa.modifiers;if(typeof j==="string"){F=ba[j]||(ba[j]=[]);if(!F[k]){F.push(k);F[k]=true}aa.specified[j]?y.def(k,s,q,u):(F.__deferMods||(F.__deferMods=[])).push([k,s,q,u])}else for(C in j)if(!(C in V)){k=j[C];F=ba[C]||(aa.modifiers[C]=[]);if(!F[k]){F.push(k);F[k]=true;aa.specified[C]&&
y([k],K)}}};y.isArray=function(j){return Da.call(j)==="[object Array]"};y.isFunction=T;y.get=function(j,k,s){if(j==="require"||j==="exports"||j==="module")y.onError(new Error("Explicit require of "+j+" is not allowed."));k=k||x.ctxName;var q;q=x.contexts[k];s=y.splitPrefix(j,s,q);q=q.defined[s.name];q===undefined&&y.onError(new Error("require: module name '"+j+"' has not been loaded yet for context: "+k));return q};y.load=function(j,k){var s=x.contexts[k],q=s.urlFetched,u=s.loaded;x.isDone=false;
u[j]||(u[j]=false);if(k!==x.ctxName)Y.push(arguments);else{u=y.nameToUrl(j,null,k);if(!q[u]){s.scriptCount+=1;y.attach(u,k,j);q[u]=true;if(s.jQuery&&!s.jQueryIncremented){s.jQuery.readyWait+=1;s.jQueryIncremented=true}}}};y.jsExtRegExp=/^\/|:|\?|\.js$/;y.normalizeName=function(j,k,s){if(j.charAt(0)===".")if(k){if(s.config.packages[k])k=[k];else{k=k.split("/");k=k.slice(0,k.length-1)}j=k.concat(j.split("/"));for(W=0;k=j[W];W++)if(k==="."){j.splice(W,1);W-=1}else if(k==="..")if(W===1)break;else if(W>
1){j.splice(W-1,2);W-=2}j=j.join("/")}return j};y.splitPrefix=function(j,k,s){var q=j.indexOf("!"),u=null;if(q!==-1){u=j.substring(0,q);j=j.substring(q+1,j.length)}j=y.normalizeName(j,k,s);return{prefix:u,name:j,fullName:u?u+"!"+j:j}};y.nameToUrl=function(j,k,s,q){var u,C,F,K;K=x.contexts[s];s=K.config;j=y.normalizeName(j,q,K);if(y.jsExtRegExp.test(j))j=j+(k?k:"");else{u=s.paths;C=s.packages;q=j.split("/");for(K=q.length;K>0;K--){F=q.slice(0,K).join("/");if(u[F]){q.splice(0,K,u[F]);break}else if(F=
C[F]){u=F.location+"/"+F.lib;if(j===F.name)u+="/"+F.main;q.splice(0,K,u);break}}j=q.join("/")+(k||".js");j=(j.charAt(0)==="/"||j.match(/^\w+:/)?"":s.baseUrl)+j}return s.urlArgs?j+((j.indexOf("?")===-1?"?":"&")+s.urlArgs):j};y.blockCheckLoaded=true;y.checkLoaded=function(j){var k=x.contexts[j||x.ctxName],s=k.config.waitSeconds*1E3,q=s&&k.startTime+s<(new Date).getTime(),u,C=k.defined,F=k.modifiers,K="",aa=false,ba=false,U,ha=x.plugins.isWaiting,ua=x.plugins.orderDeps;if(!k.isCheckLoaded){if(k.config.priorityWait)if(B(k))D(k);
else return;k.isCheckLoaded=y.blockCheckLoaded;s=k.waiting;u=k.loaded;for(U in u)if(!(U in V)){aa=true;if(!u[U])if(q)K+=U+" ";else{ba=true;break}}if(!aa&&!s.length&&(!ha||!ha(k)))k.isCheckLoaded=false;else{if(q&&K){u=new Error("require.js load timeout for modules: "+K);u.requireType="timeout";u.requireModules=K;y.onError(u)}if(ba){k.isCheckLoaded=false;if(sa||Fa)setTimeout(function(){y.checkLoaded(j)},50)}else{k.waiting=[];k.loaded={};ua&&ua(k);for(U in F)U in V||C[U]&&y.execModifiers(U,{},s,k);for(u=
0;C=s[u];u++)y.exec(C,{},s,k);k.isCheckLoaded=false;if(k.waiting.length||ha&&ha(k))y.checkLoaded(j);else if(Y.length){u=k.loaded;k=true;for(U in u)if(!(U in V))if(!u[U]){k=false;break}if(k){x.ctxName=Y[0][1];U=Y;Y=[];for(u=0;k=U[u];u++)y.load.apply(y,k)}}else{x.ctxName="_";x.isDone=true;y.callReady&&y.callReady()}}}}};y.exec=function(j,k,s,q){if(j){var u=j.name,C=j.callback;C=j.deps;var F,K,aa=q.defined,ba,U=[],ha,ua=false;if(u){if(k[u]||u in aa)return aa[u];k[u]=true}if(C)for(F=0;K=C[F];F++){K=K.name;
if(K==="require")K=da(q,u);else if(K==="exports"){K=aa[u]={};ua=true}else if(K==="module"){ha=K={id:u,uri:u?y.nameToUrl(u,null,q.contextName):undefined};ha.setExports=P(ha)}else K=K in aa?aa[K]:k[K]?undefined:y.exec(s[s[K]],k,s,q);U.push(K)}if((C=j.callback)&&y.isFunction(C)){ba=y.execCb(u,C,U);if(u)if(ua&&ba===undefined&&(!ha||!("exports"in ha)))ba=aa[u];else if(ha&&"exports"in ha)ba=aa[u]=ha.exports;else{u in aa&&!ua&&y.onError(new Error(u+" has already been defined"));aa[u]=ba}}y.execModifiers(u,
k,s,q);return ba}};y.execCb=function(j,k,s){return k.apply(null,s)};y.execModifiers=function(j,k,s,q){var u=q.modifiers,C=u[j],F,K;if(C){for(K=0;K<C.length;K++){F=C[K];F in s&&y.exec(s[s[F]],k,s,q)}delete u[j]}};y.onScriptLoad=function(j){var k=j.currentTarget||j.srcElement,s;if(j.type==="load"||Pa.test(k.readyState)){s=k.getAttribute("data-requirecontext");j=k.getAttribute("data-requiremodule");s=x.contexts[s];y.completeLoad(j,s);k.removeEventListener?k.removeEventListener("load",y.onScriptLoad,
false):k.detachEvent("onreadystatechange",y.onScriptLoad)}};y.attach=function(j,k,s,q,u){var C;if(sa){q=q||y.onScriptLoad;C=document.createElement("script");C.type=u||"text/javascript";C.charset="utf-8";C.async=!x.skipAsync[j];C.setAttribute("data-requirecontext",k);C.setAttribute("data-requiremodule",s);if(C.addEventListener)C.addEventListener("load",q,false);else{Ka=true;C.attachEvent("onreadystatechange",q)}C.src=j;Ba=C;Aa?x.head.insertBefore(C,Aa):x.head.appendChild(C);Ba=null;return C}else if(Fa){q=
x.contexts[k];k=q.loaded;k[s]=false;importScripts(j);y.completeLoad(s,q)}return null};x.baseUrl=na.baseUrl;if(sa&&(!x.baseUrl||!x.head)){ja=document.getElementsByTagName("script");va=na.baseUrlMatch?na.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(W=ja.length-1;W>-1&&(ma=ja[W]);W--){if(!x.head)x.head=ma.parentNode;if(!xa&&(xa=ma.getAttribute("data-main"))){na.deps=na.deps?na.deps.concat(xa):[xa];if(!na.baseUrl&&(z=ma.src)){z=z.split("/");z.pop();x.baseUrl=na.baseUrl=
z.length?z.join("/"):"./"}}if(!x.baseUrl&&(z=ma.src))if(c=z.match(va)){x.baseUrl=z.substring(0,c.index);break}}}y.pageLoaded=function(){if(!x.isPageLoaded){x.isPageLoaded=true;Ja&&clearInterval(Ja);if(Ha)document.readyState="complete";y.callReady()}};y.callReady=function(){var j=x.readyCalls,k,s,q;if(x.isPageLoaded&&x.isDone){if(j.length){x.readyCalls=[];for(k=0;s=j[k];k++)s()}j=x.contexts;for(q in j)if(!(q in V)){k=j[q];if(k.jQueryIncremented){k.jQuery.readyWait-=1;k.jQueryIncremented=false}}}};
y.ready=function(j){x.isPageLoaded&&x.isDone?j():x.readyCalls.push(j);return y};if(sa){if(document.addEventListener){document.addEventListener("DOMContentLoaded",y.pageLoaded,false);window.addEventListener("load",y.pageLoaded,false);if(!document.readyState){Ha=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",y.pageLoaded);if(self===self.top)Ja=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");y.pageLoaded()}}catch(j){}},
30)}document.readyState==="complete"&&y.pageLoaded()}y(na);typeof setTimeout!=="undefined"&&setTimeout(function(){var j=x.contexts[na.context||"_"];J(j);D(j)},0)})();
(function(){function T(B,D){D=D.nlsWaiting;return D[B]||(D[B]=D[D.push({_name:B})-1])}function H(B,D,S,J){var P,ca,da,V,x,W,Y="root";ca=S.split("-");da=[];V=T(B,J);for(P=ca.length;P>-1;P--){x=P?ca.slice(0,P).join("-"):"root";if(W=D[x]){if(S===J.config.locale&&!V._match)V._match=x;if(Y==="root")Y=x;V[x]=x;if(W===true){W=B.split("/");W.splice(-1,0,x);W=W.join("/");if(!J.specified[W]&&!(W in J.loaded)&&!J.defined[W]){J.defPlugin[W]="i18n";da.push(W)}}}}if(Y!==S)if(J.defined[Y])J.defined[S]=J.defined[Y];
else V[S]=Y;da.length&&require(da,J.contextName)}var la=/(^.*(^|\/)nls(\/|$))([^\/]*)\/?([^\/]*)/,M={};require.plugin({prefix:"i18n",require:function(B,D,S,J){var P,ca=J.defined[B];P=la.exec(B);if(P[5]){B=P[1]+P[5];D=T(B,J);D[P[4]]=P[4];D=J.nls[B];if(!D){J.defPlugin[B]="i18n";require([B],J.contextName);D=J.nls[B]={}}D[P[4]]=S}else{if(D=J.nls[B])require.mixin(D,ca);else D=J.nls[B]=ca;J.nlsRootLoaded[B]=true;if(P=J.nlsToLoad[B]){delete J.nlsToLoad[B];for(S=0;S<P.length;S++)H(B,D,P[S],J)}H(B,D,J.config.locale,
J)}},newContext:function(B){require.mixin(B,{nlsWaiting:[],nls:{},nlsRootLoaded:{},nlsToLoad:{}});if(!B.config.locale)B.config.locale=typeof navigator==="undefined"?"root":(navigator.language||navigator.userLanguage||"root").toLowerCase()},load:function(B,D){var S=require.s.contexts[D],J;J=la.exec(B);var P=J[4];if(J[5]){B=J[1]+J[5];J=S.nls[B];if(S.nlsRootLoaded[B]&&J)H(B,J,P,S);else{(S.nlsToLoad[B]||(S.nlsToLoad[B]=[])).push(P);S.defPlugin[B]="i18n";require([B],D)}}else if(!S.nlsRootLoaded[B]){S.defPlugin[B]=
"i18n";require.load(B,D)}},checkDeps:function(){},isWaiting:function(B){return!!B.nlsWaiting.length},orderDeps:function(B){var D,S,J,P,ca,da,V,x,W,Y,ja,ma,va=B.nlsWaiting,z;B.nlsWaiting=[];B.nlsToLoad={};for(D=0;P=va[D];D++){J=P._name;ca=B.nls[J];ja=null;da=J.split("/");W=da.slice(0,da.length-1).join("/");V=da[da.length-1];for(Y in P)if(Y!=="_name"&&!(Y in M))if(Y==="_match")ja=P[Y];else if(P[Y]!==Y)(z||(z={}))[Y]=P[Y];else{x={};da=Y.split("-");for(S=da.length;S>0;S--){ma=da.slice(0,S).join("-");
ma!=="root"&&ca[ma]&&require.mixin(x,ca[ma])}ca.root&&require.mixin(x,ca.root);B.defined[W+"/"+Y+"/"+V]=x}B.defined[J]=B.defined[W+"/"+ja+"/"+V];if(z)for(Y in z)Y in M||(B.defined[W+"/"+Y+"/"+V]=B.defined[W+"/"+z[Y]+"/"+V])}}})})();
(function(){var T=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],H=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,la=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im;if(!require.textStrip)require.textStrip=function(M){if(M){M=M.replace(H,"");var B=M.match(la);if(B)M=B[1]}else M="";return M};if(!require.getXhr)require.getXhr=function(){var M,B,D;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else for(B=0;B<3;B++){D=T[B];try{M=new ActiveXObject(D)}catch(S){}if(M){T=
[D];break}}if(!M)throw new Error("require.getXhr(): XMLHttpRequest not available");return M};if(!require.fetchText)require.fetchText=function(M,B){var D=require.getXhr();D.open("GET",M,true);D.onreadystatechange=function(){D.readyState===4&&B(D.responseText)};D.send(null)};require.plugin({prefix:"text",require:function(){},newContext:function(M){require.mixin(M,{text:{},textWaiting:[]})},load:function(M,B){var D=false,S=null,J,P=M.indexOf("."),ca=M.substring(0,P),da=M.substring(P+1,M.length),V=require.s.contexts[B],
x=V.textWaiting;P=da.indexOf("!");if(P!==-1){D=da.substring(P+1,da.length);da=da.substring(0,P);P=D.indexOf("!");if(P!==-1&&D.substring(0,P)==="strip"){S=D.substring(P+1,D.length);D="strip"}else if(D!=="strip"){S=D;D=null}}J=ca+"!"+da;P=D?J+"!"+D:J;if(S!==null&&!V.text[J])V.defined[M]=V.text[J]=S;else if(!V.text[J]&&!V.textWaiting[J]&&!V.textWaiting[P]){x[P]||(x[P]=x[x.push({name:M,key:J,fullKey:P,strip:!!D})-1]);B=require.nameToUrl(ca,"."+da,B);V.loaded[M]=false;require.fetchText(B,function(W){V.text[J]=
W;V.loaded[M]=true})}},checkDeps:function(){},isWaiting:function(M){return!!M.textWaiting.length},orderDeps:function(M){var B,D,S,J=M.textWaiting;M.textWaiting=[];for(B=0;D=J[B];B++){S=M.text[D.key];M.defined[D.name]=D.strip?require.textStrip(S):S}}})})();
(function(){function T(M){var B=M.currentTarget||M.srcElement,D,S,J,P;if(M.type==="load"||la.test(B.readyState)){S=B.getAttribute("data-requirecontext");D=B.getAttribute("data-requiremodule");M=require.s.contexts[S];J=M.orderWaiting;P=M.orderCached;P[D]=true;for(D=0;P[J[D]];D++);D>0&&require(J.splice(0,D),S);if(!J.length)M.orderCached={};setTimeout(function(){B.parentNode.removeChild(B)},15)}}var H=document.createElement("script").async||window.opera&&Object.prototype.toString.call(window.opera)===
"[object Opera]"||"MozAppearance"in document.documentElement.style,la=/^(complete|loaded)$/;require.plugin({prefix:"order",require:function(){},newContext:function(M){require.mixin(M,{orderWaiting:[],orderCached:{}})},load:function(M,B){var D=require.s.contexts[B],S=require.nameToUrl(M,null,B);require.s.skipAsync[S]=true;if(H)require([M],B);else{D.orderWaiting.push(M);D.loaded[M]=false;require.attach(S,B,M,T,"script/cache")}},checkDeps:function(){},isWaiting:function(M){return!!M.orderWaiting.length},
orderDeps:function(){}})})();
(function(T,H){function la(a,b,d){if(d===H&&a.nodeType===1){d=a.getAttribute("data-"+b);if(typeof d==="string"){try{d=d==="true"?true:d==="false"?false:d==="null"?null:!c.isNaN(d)?parseFloat(d):na.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=H}return d}function M(){return false}function B(){return true}function D(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function S(a){var b,d,e,f,h,n,m,p,G,A,N,R=[];f=[];h=c.data(this,this.nodeType?"events":"__events__");if(typeof h==="function")h=
h.events;if(!(a.liveFired===this||!h||!h.live||a.button&&a.type==="click")){if(a.namespace)N=new RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+"(\\.|$)");a.liveFired=this;var fa=h.live.slice(0);for(m=0;m<fa.length;m++){h=fa[m];h.origType.replace(ya,"")===a.type?f.push(h.selector):fa.splice(m--,1)}f=c(a.target).closest(f,a.currentTarget);p=0;for(G=f.length;p<G;p++){A=f[p];for(m=0;m<fa.length;m++){h=fa[m];if(A.selector===h.selector&&(!N||N.test(h.namespace))){n=A.elem;e=null;if(h.preType===
"mouseenter"||h.preType==="mouseleave"){a.type=h.preType;e=c(a.relatedTarget).closest(h.selector)[0]}if(!e||e!==n)R.push({elem:n,handleObj:h,level:A.level})}}}p=0;for(G=R.length;p<G;p++){f=R[p];if(d&&f.level>d)break;a.currentTarget=f.elem;a.data=f.handleObj.data;a.handleObj=f.handleObj;N=f.handleObj.origHandler.apply(f.elem,arguments);if(N===false||a.isPropagationStopped()){d=f.level;if(N===false)b=false;if(a.isImmediatePropagationStopped())break}}return b}}function J(a,b){return(a&&a!=="*"?a+".":
"")+b.replace(Ja,"`").replace(y,"&")}function P(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function ca(a,b,d){if(c.isFunction(b))return c.grep(a,function(f,h){return!!b.call(f,h,f)===d});else if(b.nodeType)return c.grep(a,function(f){return f===b===d});else if(typeof b==="string"){var e=c.grep(a,function(f){return f.nodeType===1});if(aa.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(f){return c.inArray(f,b)>=0===d})}function da(a){return c.nodeName(a,"table")?
a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function V(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var e=c.data(a[d++]),f=c.data(this,e);if(e=e&&e.events){delete f.handle;f.events={};for(var h in e)for(var n in e[h])c.event.add(this,h,e[h][n],e[h][n].data)}}})}function x(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}
function W(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight;if(d==="border")return e;c.each(b==="width"?cb:db,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);if(d==="margin")e+=parseFloat(c.css(a,"margin"+this))||0;else e-=parseFloat(c.css(a,"border"+this+"Width"))||0});return e}function Y(a,b,d,e){if(c.isArray(b)&&b.length)c.each(b,function(f,h){d||eb.test(a)?e(a,h):Y(a+"["+(typeof h==="object"||c.isArray(h)?f:"")+"]",h,d,e)});else if(!d&&b!=null&&typeof b==="object")c.isEmptyObject(b)?
e(a,""):c.each(b,function(f,h){Y(a+"["+f+"]",h,d,e)});else e(a,b)}function ja(a,b){var d={};c.each(Ta.concat.apply([],Ta.slice(0,b)),function(){d[this]=a});return d}function ma(a){if(!Qa[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if(d==="none"||d==="")d="block";Qa[a]=d}return Qa[a]}function va(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var z=T.document,c=function(){function a(){if(!b.isReady){try{z.documentElement.doScroll("left")}catch(l){setTimeout(a,
1);return}b.ready()}}var b=function(l,v){return new b.fn.init(l,v)},d=T.jQuery,e=T.$,f,h=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,n=/\S/,m=/^\s+/,p=/\s+$/,G=/\W/,A=/\d/,N=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,R=/^[\],:{}\s]*$/,fa=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,I=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,ea=/(?:^|:|,)(?:\s*\[)+/g,oa=/(webkit)[ \/]([\w.]+)/,g=/(opera)(?:.*version)?[ \/]([\w.]+)/,i=/(msie) ([\w.]+)/,o=/(mozilla)(?:.*? rv:([\w.]+))?/,r=navigator.userAgent,t=false,
w=[],L,O=Object.prototype.toString,Z=Object.prototype.hasOwnProperty,ka=Array.prototype.push,pa=Array.prototype.slice,qa=String.prototype.trim,X=Array.prototype.indexOf,za={};b.fn=b.prototype={init:function(l,v){var E,Q;if(!l)return this;if(l.nodeType){this.context=this[0]=l;this.length=1;return this}if(l==="body"&&!v&&z.body){this.context=z;this[0]=z.body;this.selector="body";this.length=1;return this}if(typeof l==="string")if((E=h.exec(l))&&(E[1]||!v))if(E[1]){Q=v?v.ownerDocument||v:z;if(l=N.exec(l))if(b.isPlainObject(v)){l=
[z.createElement(l[1])];b.fn.attr.call(l,v,true)}else l=[Q.createElement(l[1])];else{l=b.buildFragment([E[1]],[Q]);l=(l.cacheable?l.fragment.cloneNode(true):l.fragment).childNodes}return b.merge(this,l)}else{if((v=z.getElementById(E[2]))&&v.parentNode){if(v.id!==E[2])return f.find(l);this.length=1;this[0]=v}this.context=z;this.selector=l;return this}else if(!v&&!G.test(l)){this.selector=l;this.context=z;l=z.getElementsByTagName(l);return b.merge(this,l)}else return!v||v.jquery?(v||f).find(l):b(v).find(l);
else if(b.isFunction(l))return f.ready(l);if(l.selector!==H){this.selector=l.selector;this.context=l.context}return b.makeArray(l,this)},selector:"",jquery:"1.4.4",length:0,size:function(){return this.length},toArray:function(){return pa.call(this,0)},get:function(l){return l==null?this.toArray():l<0?this.slice(l)[0]:this[l]},pushStack:function(l,v,E){var Q=b();b.isArray(l)?ka.apply(Q,l):b.merge(Q,l);Q.prevObject=this;Q.context=this.context;if(v==="find")Q.selector=this.selector+(this.selector?" ":
"")+E;else if(v)Q.selector=this.selector+"."+v+"("+E+")";return Q},each:function(l,v){return b.each(this,l,v)},ready:function(l){b.bindReady();if(b.isReady)l.call(z,b);else w&&w.push(l);return this},eq:function(l){return l===-1?this.slice(l):this.slice(l,+l+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(pa.apply(this,arguments),"slice",pa.call(arguments).join(","))},map:function(l){return this.pushStack(b.map(this,function(v,E){return l.call(v,
E,v)}))},end:function(){return this.prevObject||b(null)},push:ka,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var l,v,E,Q,ga,$=arguments[0]||{},ia=1,ta=arguments.length,Ra=false;if(typeof $==="boolean"){Ra=$;$=arguments[1]||{};ia=2}if(typeof $!=="object"&&!b.isFunction($))$={};if(ta===ia){$=this;--ia}for(;ia<ta;ia++)if((l=arguments[ia])!=null)for(v in l){E=$[v];Q=l[v];if($!==Q)if(Ra&&Q&&(b.isPlainObject(Q)||(ga=b.isArray(Q)))){if(ga){ga=false;E=E&&b.isArray(E)?
E:[]}else E=E&&b.isPlainObject(E)?E:{};$[v]=b.extend(Ra,E,Q)}else if(Q!==H)$[v]=Q}return $};b.extend({noConflict:function(l){T.$=e;if(l)T.jQuery=d;return b},isReady:false,readyWait:1,ready:function(l){l===true&&b.readyWait--;if(!b.readyWait||l!==true&&!b.isReady){if(!z.body)return setTimeout(b.ready,1);b.isReady=true;if(!(l!==true&&--b.readyWait>0))if(w){var v=0,E=w;for(w=null;l=E[v++];)l.call(z,b);b.fn.trigger&&b(z).trigger("ready").unbind("ready")}}},bindReady:function(){if(!t){t=true;if(z.readyState===
"complete")return setTimeout(b.ready,1);if(z.addEventListener){z.addEventListener("DOMContentLoaded",L,false);T.addEventListener("load",b.ready,false)}else if(z.attachEvent){z.attachEvent("onreadystatechange",L);T.attachEvent("onload",b.ready);var l=false;try{l=T.frameElement==null}catch(v){}z.documentElement.doScroll&&l&&a()}}},isFunction:function(l){return b.type(l)==="function"},isArray:Array.isArray||function(l){return b.type(l)==="array"},isWindow:function(l){return l&&typeof l==="object"&&"setInterval"in
l},isNaN:function(l){return l==null||!A.test(l)||isNaN(l)},type:function(l){return l==null?String(l):za[O.call(l)]||"object"},isPlainObject:function(l){if(!l||b.type(l)!=="object"||l.nodeType||b.isWindow(l))return false;if(l.constructor&&!Z.call(l,"constructor")&&!Z.call(l.constructor.prototype,"isPrototypeOf"))return false;var v;for(v in l);return v===H||Z.call(l,v)},isEmptyObject:function(l){for(var v in l)return false;return true},error:function(l){throw l;},parseJSON:function(l){if(typeof l!==
"string"||!l)return null;l=b.trim(l);if(R.test(l.replace(fa,"@").replace(I,"]").replace(ea,"")))return T.JSON&&T.JSON.parse?T.JSON.parse(l):(new Function("return "+l))();else b.error("Invalid JSON: "+l)},noop:function(){},globalEval:function(l){if(l&&n.test(l)){var v=z.getElementsByTagName("head")[0]||z.documentElement,E=z.createElement("script");E.type="text/javascript";if(b.support.scriptEval)E.appendChild(z.createTextNode(l));else E.text=l;v.insertBefore(E,v.firstChild);v.removeChild(E)}},nodeName:function(l,
v){return l.nodeName&&l.nodeName.toUpperCase()===v.toUpperCase()},each:function(l,v,E){var Q,ga=0,$=l.length,ia=$===H||b.isFunction(l);if(E)if(ia)for(Q in l){if(v.apply(l[Q],E)===false)break}else for(;ga<$;){if(v.apply(l[ga++],E)===false)break}else if(ia)for(Q in l){if(v.call(l[Q],Q,l[Q])===false)break}else for(E=l[0];ga<$&&v.call(E,ga,E)!==false;E=l[++ga]);return l},trim:qa?function(l){return l==null?"":qa.call(l)}:function(l){return l==null?"":l.toString().replace(m,"").replace(p,"")},makeArray:function(l,
v){v=v||[];if(l!=null){var E=b.type(l);l.length==null||E==="string"||E==="function"||E==="regexp"||b.isWindow(l)?ka.call(v,l):b.merge(v,l)}return v},inArray:function(l,v){if(v.indexOf)return v.indexOf(l);for(var E=0,Q=v.length;E<Q;E++)if(v[E]===l)return E;return-1},merge:function(l,v){var E=l.length,Q=0;if(typeof v.length==="number")for(var ga=v.length;Q<ga;Q++)l[E++]=v[Q];else for(;v[Q]!==H;)l[E++]=v[Q++];l.length=E;return l},grep:function(l,v,E){var Q=[],ga;E=!!E;for(var $=0,ia=l.length;$<ia;$++){ga=
!!v(l[$],$);E!==ga&&Q.push(l[$])}return Q},map:function(l,v,E){for(var Q=[],ga,$=0,ia=l.length;$<ia;$++){ga=v(l[$],$,E);if(ga!=null)Q[Q.length]=ga}return Q.concat.apply([],Q)},guid:1,proxy:function(l,v,E){if(arguments.length===2)if(typeof v==="string"){E=l;l=E[v];v=H}else if(v&&!b.isFunction(v)){E=v;v=H}if(!v&&l)v=function(){return l.apply(E||this,arguments)};if(l)v.guid=l.guid=l.guid||v.guid||b.guid++;return v},access:function(l,v,E,Q,ga,$){var ia=l.length;if(typeof v==="object"){for(var ta in v)b.access(l,
ta,v[ta],Q,ga,E);return l}if(E!==H){Q=!$&&Q&&b.isFunction(E);for(ta=0;ta<ia;ta++)ga(l[ta],v,Q?E.call(l[ta],ta,ga(l[ta],v)):E,$);return l}return ia?ga(l[0],v):H},now:function(){return(new Date).getTime()},uaMatch:function(l){l=l.toLowerCase();l=oa.exec(l)||g.exec(l)||i.exec(l)||l.indexOf("compatible")<0&&o.exec(l)||[];return{browser:l[1]||"",version:l[2]||"0"}},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(l,v){za["[object "+v+"]"]=v.toLowerCase()});
r=b.uaMatch(r);if(r.browser){b.browser[r.browser]=true;b.browser.version=r.version}if(b.browser.webkit)b.browser.safari=true;if(X)b.inArray=function(l,v){return X.call(v,l)};if(!/\s/.test("\u00a0")){m=/^[\s\xA0]+/;p=/[\s\xA0]+$/}f=b(z);if(z.addEventListener)L=function(){z.removeEventListener("DOMContentLoaded",L,false);b.ready()};else if(z.attachEvent)L=function(){if(z.readyState==="complete"){z.detachEvent("onreadystatechange",L);b.ready()}};return T.jQuery=T.$=b}();(function(){c.support={};var a=
z.documentElement,b=z.createElement("script"),d=z.createElement("div"),e="script"+c.now();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var f=d.getElementsByTagName("*"),h=d.getElementsByTagName("a")[0],n=z.createElement("select"),m=n.appendChild(z.createElement("option"));if(!(!f||!f.length||!h)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,
htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(h.getAttribute("style")),hrefNormalized:h.getAttribute("href")==="/a",opacity:/^0.55$/.test(h.style.opacity),cssFloat:!!h.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:m.selected,deleteExpando:true,optDisabled:false,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableHiddenOffsets:true};n.disabled=true;c.support.optDisabled=
!m.disabled;b.type="text/javascript";try{b.appendChild(z.createTextNode("window."+e+"=1;"))}catch(p){}a.insertBefore(b,a.firstChild);if(T[e]){c.support.scriptEval=true;delete T[e]}try{delete b.test}catch(G){c.support.deleteExpando=false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function A(){c.support.noCloneEvent=false;d.detachEvent("onclick",A)});d.cloneNode(true).fireEvent("onclick")}d=z.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";
a=z.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var A=z.createElement("div");A.style.width=A.style.paddingLeft="1px";z.body.appendChild(A);c.boxModel=c.support.boxModel=A.offsetWidth===2;if("zoom"in A.style){A.style.display="inline";A.style.zoom=1;c.support.inlineBlockNeedsLayout=A.offsetWidth===2;A.style.display="";A.innerHTML="<div style='width:4px;'></div>";c.support.shrinkWrapBlocks=A.offsetWidth!==
2}A.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var N=A.getElementsByTagName("td");c.support.reliableHiddenOffsets=N[0].offsetHeight===0;N[0].style.display="";N[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&N[0].offsetHeight===0;A.innerHTML="";z.body.removeChild(A).style.display="none"});a=function(A){var N=z.createElement("div");A="on"+A;var R=A in N;if(!R){N.setAttribute(A,"return;");R=typeof N[A]==="function"}return R};
c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=f=h=null}})();var xa={},na=/^(?:\{.*\}|\[.*\])$/;c.extend({cache:{},uuid:0,expando:"jQuery"+c.now(),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},data:function(a,b,d){if(c.acceptData(a)){a=a==T?xa:a;var e=a.nodeType,f=e?a[c.expando]:null,h=c.cache;if(!(e&&!f&&typeof b==="string"&&d===H)){if(e)f||(a[c.expando]=f=++c.uuid);else h=a;if(typeof b==="object")if(e)h[f]=c.extend(h[f],b);else c.extend(h,
b);else if(e&&!h[f])h[f]={};a=e?h[f]:h;if(d!==H)a[b]=d;return typeof b==="string"?a[b]:a}}},removeData:function(a,b){if(c.acceptData(a)){a=a==T?xa:a;var d=a.nodeType,e=d?a[c.expando]:a,f=c.cache,h=d?f[e]:e;if(b){if(h){delete h[b];d&&c.isEmptyObject(h)&&c.removeData(a)}}else if(d&&c.support.deleteExpando)delete a[c.expando];else if(a.removeAttribute)a.removeAttribute(c.expando);else if(d)delete f[e];else for(var n in a)delete a[n]}},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];
if(b)return!(b===true||a.getAttribute("classid")!==b)}return true}});c.fn.extend({data:function(a,b){var d=null;if(typeof a==="undefined"){if(this.length){var e=this[0].attributes,f;d=c.data(this[0]);for(var h=0,n=e.length;h<n;h++){f=e[h].name;if(f.indexOf("data-")===0){f=f.substr(5);la(this[0],f,d[f])}}}return d}else if(typeof a==="object")return this.each(function(){c.data(this,a)});var m=a.split(".");m[1]=m[1]?"."+m[1]:"";if(b===H){d=this.triggerHandler("getData"+m[1]+"!",[m[0]]);if(d===H&&this.length){d=
c.data(this[0],a);d=la(this[0],a,d)}return d===H&&m[1]?this.data(m[0]):d}else return this.each(function(){var p=c(this),G=[m[0],b];p.triggerHandler("setData"+m[1]+"!",G);c.data(this,a,b);p.triggerHandler("changeData"+m[1]+"!",G)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c.data(a,b);if(!d)return e||[];if(!e||c.isArray(d))e=c.data(a,b,c.makeArray(d));else e.push(d);return e}},dequeue:function(a,b){b=
b||"fx";var d=c.queue(a,b),e=d.shift();if(e==="inprogress")e=d.shift();if(e){b==="fx"&&d.unshift("inprogress");e.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===H)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,
function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var Ha=/[\n\t]/g,Ia=/\s+/,Oa=/\r/g,Ea=/^(?:href|src|style)$/,sa=/^(?:button|input)$/i,Fa=/^(?:button|input|object|select|textarea)$/i,Pa=/^a(?:rea)?$/i,Da=/^(?:radio|checkbox)$/i;c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};
c.fn.extend({attr:function(a,b){return c.access(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(G){var A=c(this);A.addClass(a.call(this,G,A.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(Ia),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1)if(f.className){for(var h=" "+f.className+" ",n=f.className,m=0,p=b.length;m<
p;m++)if(h.indexOf(" "+b[m]+" ")<0)n+=" "+b[m];f.className=c.trim(n)}else f.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(p){var G=c(this);G.removeClass(a.call(this,p,G.attr("class")))});if(a&&typeof a==="string"||a===H)for(var b=(a||"").split(Ia),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1&&f.className)if(a){for(var h=(" "+f.className+" ").replace(Ha," "),n=0,m=b.length;n<m;n++)h=h.replace(" "+b[n]+" "," ");f.className=c.trim(h)}else f.className=
""}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(f){var h=c(this);h.toggleClass(a.call(this,f,h.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var f,h=0,n=c(this),m=b,p=a.split(Ia);f=p[h++];){m=e?m:!n.hasClass(f);n[m?"addClass":"removeClass"](f)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,
"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ha," ").indexOf(a)>-1)return true;return false},val:function(a){if(!arguments.length){var b=this[0];if(b){if(c.nodeName(b,"option")){var d=b.attributes.value;return!d||d.specified?b.value:b.text}if(c.nodeName(b,"select")){var e=b.selectedIndex;d=[];var f=b.options;b=b.type==="select-one";if(e<0)return null;var h=b?e:0;for(e=b?e+1:f.length;h<e;h++){var n=f[h];if(n.selected&&
(c.support.optDisabled?!n.disabled:n.getAttribute("disabled")===null)&&(!n.parentNode.disabled||!c.nodeName(n.parentNode,"optgroup"))){a=c(n).val();if(b)return a;d.push(a)}}return d}if(Da.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(Oa,"")}return H}var m=c.isFunction(a);return this.each(function(p){var G=c(this),A=a;if(this.nodeType===1){if(m)A=a.call(this,p,G.val());if(A==null)A="";else if(typeof A==="number")A+="";else if(c.isArray(A))A=
c.map(A,function(R){return R==null?"":R+""});if(c.isArray(A)&&Da.test(this.type))this.checked=c.inArray(G.val(),A)>=0;else if(c.nodeName(this,"select")){var N=c.makeArray(A);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),N)>=0});if(!N.length)this.selectedIndex=-1}else this.value=A}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,e){if(!a||a.nodeType===3||a.nodeType===8)return H;if(e&&b in c.attrFn)return c(a)[b](d);
e=a.nodeType!==1||!c.isXMLDoc(a);var f=d!==H;b=e&&c.props[b]||b;var h=Ea.test(b);if((b in a||a[b]!==H)&&e&&!h){if(f){b==="type"&&sa.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");if(d===null)a.nodeType===1&&a.removeAttribute(b);else a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:Fa.test(a.nodeName)||Pa.test(a.nodeName)&&a.href?0:H;return a[b]}if(!c.support.style&&
e&&b==="style"){if(f)a.style.cssText=""+d;return a.style.cssText}f&&a.setAttribute(b,""+d);if(!a.attributes[b]&&a.hasAttribute&&!a.hasAttribute(b))return H;a=!c.support.hrefNormalized&&e&&h?a.getAttribute(b,2):a.getAttribute(b);return a===null?H:a}});var ya=/\.(.*)$/,Ga=/^(?:textarea|input|select)$/i,Ja=/\./g,y=/ /g,Aa=/[^\w\s.|`]/g,wa=function(a){return a.replace(Aa,"\\$&")},Ka={focusin:0,focusout:0};c.event={add:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){if(c.isWindow(a)&&a!==T&&!a.frameElement)a=
T;if(d===false)d=M;else if(!d)return;var f,h;if(d.handler){f=d;d=f.handler}if(!d.guid)d.guid=c.guid++;if(h=c.data(a)){var n=a.nodeType?"events":"__events__",m=h[n],p=h.handle;if(typeof m==="function"){p=m.handle;m=m.events}else if(!m){a.nodeType||(h[n]=h=function(){});h.events=m={}}if(!p)h.handle=p=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(p.elem,arguments):H};p.elem=a;b=b.split(" ");for(var G=0,A;n=b[G++];){h=f?c.extend({},f):{handler:d,data:e};if(n.indexOf(".")>
-1){A=n.split(".");n=A.shift();h.namespace=A.slice(0).sort().join(".")}else{A=[];h.namespace=""}h.type=n;if(!h.guid)h.guid=d.guid;var N=m[n],R=c.event.special[n]||{};if(!N){N=m[n]=[];if(!R.setup||R.setup.call(a,e,A,p)===false)if(a.addEventListener)a.addEventListener(n,p,false);else a.attachEvent&&a.attachEvent("on"+n,p)}if(R.add){R.add.call(a,h);if(!h.handler.guid)h.handler.guid=d.guid}N.push(h);c.event.global[n]=true}a=null}}},global:{},remove:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===
8)){if(d===false)d=M;var f,h,n=0,m,p,G,A,N,R,fa=a.nodeType?"events":"__events__",I=c.data(a),ea=I&&I[fa];if(I&&ea){if(typeof ea==="function"){I=ea;ea=ea.events}if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(f in ea)c.event.remove(a,f+b)}else{for(b=b.split(" ");f=b[n++];){A=f;m=f.indexOf(".")<0;p=[];if(!m){p=f.split(".");f=p.shift();G=new RegExp("(^|\\.)"+c.map(p.slice(0).sort(),wa).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(N=ea[f])if(d){A=c.event.special[f]||
{};for(h=e||0;h<N.length;h++){R=N[h];if(d.guid===R.guid){if(m||G.test(R.namespace)){e==null&&N.splice(h--,1);A.remove&&A.remove.call(a,R)}if(e!=null)break}}if(N.length===0||e!=null&&N.length===1){if(!A.teardown||A.teardown.call(a,p)===false)c.removeEvent(a,f,I.handle);delete ea[f]}}else for(h=0;h<N.length;h++){R=N[h];if(m||G.test(R.namespace)){c.event.remove(a,A,R.handler,h);N.splice(h--,1)}}}if(c.isEmptyObject(ea)){if(b=I.handle)b.elem=null;delete I.events;delete I.handle;if(typeof I==="function")c.removeData(a,
fa);else c.isEmptyObject(I)&&c.removeData(a)}}}}},trigger:function(a,b,d,e){var f=a.type||a;if(!e){a=typeof a==="object"?a[c.expando]?a:c.extend(c.Event(f),a):c.Event(f);if(f.indexOf("!")>=0){a.type=f=f.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[f]&&c.each(c.cache,function(){this.events&&this.events[f]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return H;a.result=H;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(e=d.nodeType?
c.data(d,"handle"):(c.data(d,"__events__")||{}).handle)&&e.apply(d,b);e=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+f]&&d["on"+f].apply(d,b)===false){a.result=false;a.preventDefault()}}catch(h){}if(!a.isPropagationStopped()&&e)c.event.trigger(a,b,e,true);else if(!a.isDefaultPrevented()){var n;e=a.target;var m=f.replace(ya,""),p=c.nodeName(e,"a")&&m==="click",G=c.event.special[m]||{};if((!G._default||G._default.call(d,a)===false)&&!p&&!(e&&e.nodeName&&
c.noData[e.nodeName.toLowerCase()])){try{if(e[m]){if(n=e["on"+m])e["on"+m]=null;c.event.triggered=true;e[m]()}}catch(A){}if(n)e["on"+m]=n;c.event.triggered=false}}},handle:function(a){var b,d,e,f;d=[];var h=c.makeArray(arguments);a=h[0]=c.event.fix(a||T.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){e=a.type.split(".");a.type=e.shift();d=e.slice(0).sort();e=new RegExp("(^|\\.)"+d.join("\\.(?:.*\\.)?")+"(\\.|$)")}a.namespace=a.namespace||d.join(".");f=c.data(this,this.nodeType?
"events":"__events__");if(typeof f==="function")f=f.events;d=(f||{})[a.type];if(f&&d){d=d.slice(0);f=0;for(var n=d.length;f<n;f++){var m=d[f];if(b||e.test(m.namespace)){a.handler=m.handler;a.data=m.data;a.handleObj=m;m=m.handler.apply(this,h);if(m!==H){a.result=m;if(m===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[c.expando])return a;var b=a;a=c.Event(b);for(var d=this.props.length,e;d;){e=this.props[--d];a[e]=b[e]}if(!a.target)a.target=a.srcElement||z;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=z.documentElement;d=z.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(a.which==null&&(a.charCode!=null||a.keyCode!=null))a.which=a.charCode!=null?a.charCode:a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==H)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,J(a.origType,a.selector),c.extend({},a,{handler:S,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,
J(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};c.removeEvent=z.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=a;this.timeStamp=
c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=B;var a=this.originalEvent;if(a)if(a.preventDefault)a.preventDefault();else a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=B;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=B;this.stopPropagation()},isDefaultPrevented:M,isPropagationStopped:M,isImmediatePropagationStopped:M};
var Ba=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},j=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?j:Ba,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?j:Ba)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length){a.liveFired=H;return D("submit",this,arguments)}});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13){a.liveFired=H;return D("submit",this,arguments)}})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var k,
s=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(e){return e.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},q=function(a,b){var d=a.target,e,f;if(!(!Ga.test(d.nodeName)||d.readOnly)){e=c.data(d,"_change_data");f=s(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",f);if(!(e===H||f===e))if(e!=null||f){a.type="change";a.liveFired=
H;return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:q,beforedeactivate:q,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return q.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return q.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",s(a))}},setup:function(){if(this.type===
"file")return false;for(var a in k)c.event.add(this,a+".specialChange",k[a]);return Ga.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return Ga.test(this.nodeName)}};k=c.event.special.change.filters;k.focus=k.beforeactivate}z.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(e){e=c.event.fix(e);e.type=b;return c.event.trigger(e,null,e.target)}c.event.special[b]={setup:function(){Ka[b]++===0&&z.addEventListener(a,d,true)},teardown:function(){--Ka[b]===
0&&z.removeEventListener(a,d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,e,f){if(typeof d==="object"){for(var h in d)this[b](h,e,d[h],f);return this}if(c.isFunction(e)||e===false){f=e;e=H}var n=b==="one"?c.proxy(f,function(p){c(this).unbind(p,n);return f.apply(this,arguments)}):f;if(d==="unload"&&b!=="one")this.one(d,e,f);else{h=0;for(var m=this.length;h<m;h++)c.event.add(this[h],d,n,e)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,
a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,e){return this.live(b,d,e,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<
b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(e){var f=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,f+1);e.preventDefault();return b[f].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var u={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,e,f,h){var n,m=0,p,G,A=h||this.selector;h=h?this:c(this.context);if(typeof d==="object"&&
!d.preventDefault){for(n in d)h[b](n,e,d[n],A);return this}if(c.isFunction(e)){f=e;e=H}for(d=(d||"").split(" ");(n=d[m++])!=null;){p=ya.exec(n);G="";if(p){G=p[0];n=n.replace(ya,"")}if(n==="hover")d.push("mouseenter"+G,"mouseleave"+G);else{p=n;if(n==="focus"||n==="blur"){d.push(u[n]+G);n+=G}else n=(u[n]||n)+G;if(b==="live"){G=0;for(var N=h.length;G<N;G++)c.event.add(h[G],"live."+J(n,A),{data:e,selector:A,handler:f,origType:n,origHandler:f,preType:p})}else h.unbind("live."+J(n,A),f)}}return this}});
c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),function(a,b){c.fn[b]=function(d,e){if(e==null){e=d;d=null}return arguments.length>0?this.bind(b,d,e):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});T.attachEvent&&!T.addEventListener&&c(T).bind("unload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});
(function(){function a(g,i,o,r,t,w){t=0;for(var L=r.length;t<L;t++){var O=r[t];if(O){var Z=false;for(O=O[g];O;){if(O.sizcache===o){Z=r[O.sizset];break}if(O.nodeType===1&&!w){O.sizcache=o;O.sizset=t}if(O.nodeName.toLowerCase()===i){Z=O;break}O=O[g]}r[t]=Z}}}function b(g,i,o,r,t,w){t=0;for(var L=r.length;t<L;t++){var O=r[t];if(O){var Z=false;for(O=O[g];O;){if(O.sizcache===o){Z=r[O.sizset];break}if(O.nodeType===1){if(!w){O.sizcache=o;O.sizset=t}if(typeof i!=="string"){if(O===i){Z=true;break}}else if(m.filter(i,
[O]).length>0){Z=O;break}}O=O[g]}r[t]=Z}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,f=Object.prototype.toString,h=false,n=true;[0,0].sort(function(){n=false;return 0});var m=function(g,i,o,r){o=o||[];var t=i=i||z;if(i.nodeType!==1&&i.nodeType!==9)return[];if(!g||typeof g!=="string")return o;var w,L,O,Z,ka,pa=true,qa=m.isXML(i),X=[],za=g;do{d.exec("");if(w=d.exec(za)){za=w[3];X.push(w[1]);if(w[2]){Z=
w[3];break}}}while(w);if(X.length>1&&G.exec(g))if(X.length===2&&p.relative[X[0]])L=oa(X[0]+X[1],i);else for(L=p.relative[X[0]]?[i]:m(X.shift(),i);X.length;){g=X.shift();if(p.relative[g])g+=X.shift();L=oa(g,L)}else{if(!r&&X.length>1&&i.nodeType===9&&!qa&&p.match.ID.test(X[0])&&!p.match.ID.test(X[X.length-1])){w=m.find(X.shift(),i,qa);i=w.expr?m.filter(w.expr,w.set)[0]:w.set[0]}if(i){w=r?{expr:X.pop(),set:R(r)}:m.find(X.pop(),X.length===1&&(X[0]==="~"||X[0]==="+")&&i.parentNode?i.parentNode:i,qa);L=
w.expr?m.filter(w.expr,w.set):w.set;if(X.length>0)O=R(L);else pa=false;for(;X.length;){w=ka=X.pop();if(p.relative[ka])w=X.pop();else ka="";if(w==null)w=i;p.relative[ka](O,w,qa)}}else O=[]}O||(O=L);O||m.error(ka||g);if(f.call(O)==="[object Array]")if(pa)if(i&&i.nodeType===1)for(g=0;O[g]!=null;g++){if(O[g]&&(O[g]===true||O[g].nodeType===1&&m.contains(i,O[g])))o.push(L[g])}else for(g=0;O[g]!=null;g++)O[g]&&O[g].nodeType===1&&o.push(L[g]);else o.push.apply(o,O);else R(O,o);if(Z){m(Z,t,o,r);m.uniqueSort(o)}return o};
m.uniqueSort=function(g){if(I){h=n;g.sort(I);if(h)for(var i=1;i<g.length;i++)g[i]===g[i-1]&&g.splice(i--,1)}return g};m.matches=function(g,i){return m(g,null,null,i)};m.matchesSelector=function(g,i){return m(i,null,null,[g]).length>0};m.find=function(g,i,o){var r;if(!g)return[];for(var t=0,w=p.order.length;t<w;t++){var L,O=p.order[t];if(L=p.leftMatch[O].exec(g)){var Z=L[1];L.splice(1,1);if(Z.substr(Z.length-1)!=="\\"){L[1]=(L[1]||"").replace(/\\/g,"");r=p.find[O](L,i,o);if(r!=null){g=g.replace(p.match[O],
"");break}}}}r||(r=i.getElementsByTagName("*"));return{set:r,expr:g}};m.filter=function(g,i,o,r){for(var t,w,L=g,O=[],Z=i,ka=i&&i[0]&&m.isXML(i[0]);g&&i.length;){for(var pa in p.filter)if((t=p.leftMatch[pa].exec(g))!=null&&t[2]){var qa,X,za=p.filter[pa];X=t[1];w=false;t.splice(1,1);if(X.substr(X.length-1)!=="\\"){if(Z===O)O=[];if(p.preFilter[pa])if(t=p.preFilter[pa](t,Z,o,O,r,ka)){if(t===true)continue}else w=qa=true;if(t)for(var l=0;(X=Z[l])!=null;l++)if(X){qa=za(X,t,l,Z);var v=r^!!qa;if(o&&qa!=null)if(v)w=
true;else Z[l]=false;else if(v){O.push(X);w=true}}if(qa!==H){o||(Z=O);g=g.replace(p.match[pa],"");if(!w)return[];break}}}if(g===L)if(w==null)m.error(g);else break;L=g}return Z};m.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var p=m.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,i){var o=typeof i==="string",r=o&&!/\W/.test(i);o=o&&!r;if(r)i=i.toLowerCase();r=0;for(var t=g.length,
w;r<t;r++)if(w=g[r]){for(;(w=w.previousSibling)&&w.nodeType!==1;);g[r]=o||w&&w.nodeName.toLowerCase()===i?w||false:w===i}o&&m.filter(i,g,true)},">":function(g,i){var o,r=typeof i==="string",t=0,w=g.length;if(r&&!/\W/.test(i))for(i=i.toLowerCase();t<w;t++){if(o=g[t]){o=o.parentNode;g[t]=o.nodeName.toLowerCase()===i?o:false}}else{for(;t<w;t++)if(o=g[t])g[t]=r?o.parentNode:o.parentNode===i;r&&m.filter(i,g,true)}},"":function(g,i,o){var r,t=e++,w=b;if(typeof i==="string"&&!/\W/.test(i)){r=i=i.toLowerCase();
w=a}w("parentNode",i,t,g,r,o)},"~":function(g,i,o){var r,t=e++,w=b;if(typeof i==="string"&&!/\W/.test(i)){r=i=i.toLowerCase();w=a}w("previousSibling",i,t,g,r,o)}},find:{ID:function(g,i,o){if(typeof i.getElementById!=="undefined"&&!o)return(g=i.getElementById(g[1]))&&g.parentNode?[g]:[]},NAME:function(g,i){if(typeof i.getElementsByName!=="undefined"){var o=[];i=i.getElementsByName(g[1]);for(var r=0,t=i.length;r<t;r++)i[r].getAttribute("name")===g[1]&&o.push(i[r]);return o.length===0?null:o}},TAG:function(g,
i){return i.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,i,o,r,t,w){g=" "+g[1].replace(/\\/g,"")+" ";if(w)return g;w=0;for(var L;(L=i[w])!=null;w++)if(L)if(t^(L.className&&(" "+L.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))o||r.push(L);else if(o)i[w]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var i=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&
"0n+"+g[2]||g[2]);g[2]=i[1]+(i[2]||1)-0;g[3]=i[3]-0}g[0]=e++;return g},ATTR:function(g,i,o,r,t,w){i=g[1].replace(/\\/g,"");if(!w&&p.attrMap[i])g[1]=p.attrMap[i];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,i,o,r,t){if(g[1]==="not")if((d.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=m(g[3],null,null,i);else{g=m.filter(g[3],i,o,true^t);o||r.push.apply(r,g);return false}else if(p.match.POS.test(g[0])||p.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},
filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},empty:function(g){return!g.firstChild},has:function(g,i,o){return!!m(o[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===
g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,i){return i===0},last:function(g,i,o,r){return i===r.length-1},even:function(g,i){return i%2===
0},odd:function(g,i){return i%2===1},lt:function(g,i,o){return i<o[3]-0},gt:function(g,i,o){return i>o[3]-0},nth:function(g,i,o){return o[3]-0===i},eq:function(g,i,o){return o[3]-0===i}},filter:{PSEUDO:function(g,i,o,r){var t=i[1],w=p.filters[t];if(w)return w(g,o,i,r);else if(t==="contains")return(g.textContent||g.innerText||m.getText([g])||"").indexOf(i[3])>=0;else if(t==="not"){i=i[3];o=0;for(r=i.length;o<r;o++)if(i[o]===g)return false;return true}else m.error("Syntax error, unrecognized expression: "+
t)},CHILD:function(g,i){var o=i[1],r=g;switch(o){case "only":case "first":for(;r=r.previousSibling;)if(r.nodeType===1)return false;if(o==="first")return true;r=g;case "last":for(;r=r.nextSibling;)if(r.nodeType===1)return false;return true;case "nth":o=i[2];var t=i[3];if(o===1&&t===0)return true;i=i[0];var w=g.parentNode;if(w&&(w.sizcache!==i||!g.nodeIndex)){var L=0;for(r=w.firstChild;r;r=r.nextSibling)if(r.nodeType===1)r.nodeIndex=++L;w.sizcache=i}g=g.nodeIndex-t;return o===0?g===0:g%o===0&&g/o>=
0}},ID:function(g,i){return g.nodeType===1&&g.getAttribute("id")===i},TAG:function(g,i){return i==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===i},CLASS:function(g,i){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(i)>-1},ATTR:function(g,i){var o=i[1];g=p.attrHandle[o]?p.attrHandle[o](g):g[o]!=null?g[o]:g.getAttribute(o);o=g+"";var r=i[2];i=i[4];return g==null?r==="!=":r==="="?o===i:r==="*="?o.indexOf(i)>=0:r==="~="?(" "+o+" ").indexOf(i)>=0:!i?o&&g!==false:r==="!="?o!==i:r==="^="?
o.indexOf(i)===0:r==="$="?o.substr(o.length-i.length)===i:r==="|="?o===i||o.substr(0,i.length+1)===i+"-":false},POS:function(g,i,o,r){var t=p.setFilters[i[2]];if(t)return t(g,o,i,r)}}},G=p.match.POS,A=function(g,i){return"\\"+(i-0+1)};for(var N in p.match){p.match[N]=new RegExp(p.match[N].source+/(?![^\[]*\])(?![^\(]*\))/.source);p.leftMatch[N]=new RegExp(/(^(?:.|\r|\n)*?)/.source+p.match[N].source.replace(/\\(\d+)/g,A))}var R=function(g,i){g=Array.prototype.slice.call(g,0);if(i){i.push.apply(i,g);
return i}return g};try{Array.prototype.slice.call(z.documentElement.childNodes,0)}catch(fa){R=function(g,i){var o=0;i=i||[];if(f.call(g)==="[object Array]")Array.prototype.push.apply(i,g);else if(typeof g.length==="number")for(var r=g.length;o<r;o++)i.push(g[o]);else for(;g[o];o++)i.push(g[o]);return i}}var I,ea;if(z.documentElement.compareDocumentPosition)I=function(g,i){if(g===i){h=true;return 0}if(!g.compareDocumentPosition||!i.compareDocumentPosition)return g.compareDocumentPosition?-1:1;return g.compareDocumentPosition(i)&
4?-1:1};else{I=function(g,i){var o,r,t=[],w=[];o=g.parentNode;r=i.parentNode;var L=o;if(g===i){h=true;return 0}else if(o===r)return ea(g,i);else if(o){if(!r)return 1}else return-1;for(;L;){t.unshift(L);L=L.parentNode}for(L=r;L;){w.unshift(L);L=L.parentNode}o=t.length;r=w.length;for(L=0;L<o&&L<r;L++)if(t[L]!==w[L])return ea(t[L],w[L]);return L===o?ea(g,w[L],-1):ea(t[L],i,1)};ea=function(g,i,o){if(g===i)return o;for(g=g.nextSibling;g;){if(g===i)return-1;g=g.nextSibling}return 1}}m.getText=function(g){for(var i=
"",o,r=0;g[r];r++){o=g[r];if(o.nodeType===3||o.nodeType===4)i+=o.nodeValue;else if(o.nodeType!==8)i+=m.getText(o.childNodes)}return i};(function(){var g=z.createElement("div"),i="script"+(new Date).getTime(),o=z.documentElement;g.innerHTML="<a name='"+i+"'/>";o.insertBefore(g,o.firstChild);if(z.getElementById(i)){p.find.ID=function(r,t,w){if(typeof t.getElementById!=="undefined"&&!w)return(t=t.getElementById(r[1]))?t.id===r[1]||typeof t.getAttributeNode!=="undefined"&&t.getAttributeNode("id").nodeValue===
r[1]?[t]:H:[]};p.filter.ID=function(r,t){var w=typeof r.getAttributeNode!=="undefined"&&r.getAttributeNode("id");return r.nodeType===1&&w&&w.nodeValue===t}}o.removeChild(g);o=g=null})();(function(){var g=z.createElement("div");g.appendChild(z.createComment(""));if(g.getElementsByTagName("*").length>0)p.find.TAG=function(i,o){o=o.getElementsByTagName(i[1]);if(i[1]==="*"){i=[];for(var r=0;o[r];r++)o[r].nodeType===1&&i.push(o[r]);o=i}return o};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!==
"undefined"&&g.firstChild.getAttribute("href")!=="#")p.attrHandle.href=function(i){return i.getAttribute("href",2)};g=null})();z.querySelectorAll&&function(){var g=m,i=z.createElement("div");i.innerHTML="<p class='TEST'></p>";if(!(i.querySelectorAll&&i.querySelectorAll(".TEST").length===0)){m=function(r,t,w,L){t=t||z;r=r.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!L&&!m.isXML(t))if(t.nodeType===9)try{return R(t.querySelectorAll(r),w)}catch(O){}else if(t.nodeType===1&&t.nodeName.toLowerCase()!==
"object"){var Z=t.getAttribute("id"),ka=Z||"__sizzle__";Z||t.setAttribute("id",ka);try{return R(t.querySelectorAll("#"+ka+" "+r),w)}catch(pa){}finally{Z||t.removeAttribute("id")}}return g(r,t,w,L)};for(var o in g)m[o]=g[o];i=null}}();(function(){var g=z.documentElement,i=g.matchesSelector||g.mozMatchesSelector||g.webkitMatchesSelector||g.msMatchesSelector,o=false;try{i.call(z.documentElement,"[test!='']:sizzle")}catch(r){o=true}if(i)m.matchesSelector=function(t,w){w=w.replace(/\=\s*([^'"\]]*)\s*\]/g,
"='$1']");if(!m.isXML(t))try{if(o||!p.match.PSEUDO.test(w)&&!/!=/.test(w))return i.call(t,w)}catch(L){}return m(w,null,null,[t]).length>0}})();(function(){var g=z.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){p.order.splice(1,0,"CLASS");p.find.CLASS=function(i,o,r){if(typeof o.getElementsByClassName!=="undefined"&&
!r)return o.getElementsByClassName(i[1])};g=null}}})();m.contains=z.documentElement.contains?function(g,i){return g!==i&&(g.contains?g.contains(i):true)}:z.documentElement.compareDocumentPosition?function(g,i){return!!(g.compareDocumentPosition(i)&16)}:function(){return false};m.isXML=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false};var oa=function(g,i){var o,r=[],t="";for(i=i.nodeType?[i]:i;o=p.match.PSEUDO.exec(g);){t+=o[0];g=g.replace(p.match.PSEUDO,"")}g=
p.relative[g]?g+"*":g;o=0;for(var w=i.length;o<w;o++)m(g,i[o],r);return m.filter(t,r)};c.find=m;c.expr=m.selectors;c.expr[":"]=c.expr.filters;c.unique=m.uniqueSort;c.text=m.getText;c.isXMLDoc=m.isXML;c.contains=m.contains})();var C=/Until$/,F=/^(?:parents|prevUntil|prevAll)/,K=/,/,aa=/^.[^:#\[\.,]*$/,ba=Array.prototype.slice,U=c.expr.match.POS;c.fn.extend({find:function(a){for(var b=this.pushStack("","find",a),d=0,e=0,f=this.length;e<f;e++){d=b.length;c.find(a,this[e],b);if(e>0)for(var h=d;h<b.length;h++)for(var n=
0;n<d;n++)if(b[n]===b[h]){b.splice(h--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(ca(this,a,false),"not",a)},filter:function(a){return this.pushStack(ca(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>0},closest:function(a,b){var d=[],e,f,h=this[0];if(c.isArray(a)){var n,m={},p=1;if(h&&a.length){e=0;for(f=a.length;e<f;e++){n=a[e];
m[n]||(m[n]=c.expr.match.POS.test(n)?c(n,b||this.context):n)}for(;h&&h.ownerDocument&&h!==b;){for(n in m){a=m[n];if(a.jquery?a.index(h)>-1:c(h).is(a))d.push({selector:n,elem:h,level:p})}h=h.parentNode;p++}}return d}n=U.test(a)?c(a,b||this.context):null;e=0;for(f=this.length;e<f;e++)for(h=this[e];h;)if(n?n.index(h)>-1:c.find.matchesSelector(h,a)){d.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||h===b)break}d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){if(!a||
typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(P(a[0])||P(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",
d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?
a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);C.test(a)||(e=d);if(e&&typeof e==="string")f=c.filter(e,f);f=this.length>1?c.unique(f):f;if((this.length>1||K.test(e))&&F.test(a))f=f.reverse();return this.pushStack(f,a,ba.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=
a[b];a&&a.nodeType!==9&&(d===H||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},nth:function(a,b,d){b=b||1;for(var e=0;a;a=a[d])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var ha=/ jQuery\d+="(?:\d+|null)"/g,ua=/^\s+/,Ua=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,Va=/<([\w:]+)/,fb=/<tbody/i,gb=/<|&#?\w+;/,Wa=/<(?:script|object|embed|option|style)/i,
Xa=/checked\s*(?:[^=]|=\s*.checked.)/i,hb=/\=([^="'>\s]+\/)>/g,ra={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};ra.optgroup=ra.option;ra.tbody=ra.tfoot=ra.colgroup=ra.caption=ra.thead;ra.th=ra.td;if(!c.support.htmlSerialize)ra._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==H)return this.empty().append((this[0]&&this[0].ownerDocument||z).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length){if(!b&&e.nodeType===1){c.cleanData(e.getElementsByTagName("*"));c.cleanData([e])}e.parentNode&&e.parentNode.removeChild(e)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,e=this.ownerDocument;if(!d){d=e.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(ha,"").replace(hb,'="$1">').replace(ua,"")],e)[0]}else return this.cloneNode(true)});if(a===true){V(this,b);V(this.find("*"),b.find("*"))}return b},html:function(a){if(a===H)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(ha,""):null;
else if(typeof a==="string"&&!Wa.test(a)&&(c.support.leadingWhitespace||!ua.test(a))&&!ra[(Va.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ua,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(e){this.empty().append(a)}}else c.isFunction(a)?this.each(function(f){var h=c(this);h.html(a.call(this,f,h.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=
c(this),e=d.html();d.replaceWith(a.call(this,b,e))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){var e,f,h,n=a[0],m=[];if(!c.support.checkClone&&arguments.length===3&&typeof n==="string"&&Xa.test(n))return this.each(function(){c(this).domManip(a,
b,d,true)});if(c.isFunction(n))return this.each(function(A){var N=c(this);a[0]=n.call(this,A,b?N.html():H);N.domManip(a,b,d)});if(this[0]){e=n&&n.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,m);h=e.fragment;if(f=h.childNodes.length===1?(h=h.firstChild):h.firstChild){b=b&&c.nodeName(f,"tr");for(var p=0,G=this.length;p<G;p++)d.call(b?da(this[p],f):this[p],p>0||e.cacheable||this.length>1?h.cloneNode(true):h)}m.length&&c.each(m,
x)}return this}});c.buildFragment=function(a,b,d){var e,f,h;b=b&&b[0]?b[0].ownerDocument||b[0]:z;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===z&&!Wa.test(a[0])&&(c.support.checkClone||!Xa.test(a[0]))){f=true;if(h=c.fragments[a[0]])if(h!==1)e=h}if(!e){e=b.createDocumentFragment();c.clean(a,b,e,d)}if(f)c.fragments[a[0]]=h?e:1;return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},
function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var f=this.length===1&&this[0].parentNode;if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{f=0;for(var h=d.length;f<h;f++){var n=(f>0?this.clone(true):this).get();c(d[f])[b](n);e=e.concat(n)}return this.pushStack(e,a,d.selector)}}});c.extend({clean:function(a,b,d,e){b=b||z;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||z;for(var f=[],h=0,n;(n=a[h])!=null;h++){if(typeof n===
"number")n+="";if(n){if(typeof n==="string"&&!gb.test(n))n=b.createTextNode(n);else if(typeof n==="string"){n=n.replace(Ua,"<$1></$2>");var m=(Va.exec(n)||["",""])[1].toLowerCase(),p=ra[m]||ra._default,G=p[0],A=b.createElement("div");for(A.innerHTML=p[1]+n+p[2];G--;)A=A.lastChild;if(!c.support.tbody){G=fb.test(n);m=m==="table"&&!G?A.firstChild&&A.firstChild.childNodes:p[1]==="<table>"&&!G?A.childNodes:[];for(p=m.length-1;p>=0;--p)c.nodeName(m[p],"tbody")&&!m[p].childNodes.length&&m[p].parentNode.removeChild(m[p])}!c.support.leadingWhitespace&&
ua.test(n)&&A.insertBefore(b.createTextNode(ua.exec(n)[0]),A.firstChild);n=A.childNodes}if(n.nodeType)f.push(n);else f=c.merge(f,n)}}if(d)for(h=0;f[h];h++)if(e&&c.nodeName(f[h],"script")&&(!f[h].type||f[h].type.toLowerCase()==="text/javascript"))e.push(f[h].parentNode?f[h].parentNode.removeChild(f[h]):f[h]);else{f[h].nodeType===1&&f.splice.apply(f,[h+1,0].concat(c.makeArray(f[h].getElementsByTagName("script"))));d.appendChild(f[h])}return f},cleanData:function(a){for(var b,d,e=c.cache,f=c.event.special,
h=c.support.deleteExpando,n=0,m;(m=a[n])!=null;n++)if(!(m.nodeName&&c.noData[m.nodeName.toLowerCase()]))if(d=m[c.expando]){if((b=e[d])&&b.events)for(var p in b.events)f[p]?c.event.remove(m,p):c.removeEvent(m,p,b.handle);if(h)delete m[c.expando];else m.removeAttribute&&m.removeAttribute(c.expando);delete e[d]}}});var Ya=/alpha\([^)]*\)/i,ib=/opacity=([^)]*)/,jb=/-([a-z])/ig,kb=/([A-Z])/g,Za=/^-?\d+(?:px)?$/i,lb=/^-?\d/,mb={position:"absolute",visibility:"hidden",display:"block"},cb=["Left","Right"],
db=["Top","Bottom"],La,$a,Ma,nb=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){if(arguments.length===2&&b===H)return this;return c.access(this,a,b,true,function(d,e,f){return f!==H?c.style(d,e,f):c.css(d,e)})};c.extend({cssHooks:{opacity:{get:function(a,b){if(b){a=La(a,"opacity","opacity");return a===""?"1":a}else return a.style.opacity}}},cssNumber:{zIndex:true,fontWeight:true,opacity:true,zoom:true,lineHeight:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,
b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||!a.style)){var f,h=c.camelCase(b),n=a.style,m=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==H){if(!(typeof d==="number"&&isNaN(d)||d==null)){if(typeof d==="number"&&!c.cssNumber[h])d+="px";if(!m||!("set"in m)||(d=m.set(a,d))!==H)try{n[b]=d}catch(p){}}}else{if(m&&"get"in m&&(f=m.get(a,false,e))!==H)return f;return n[b]}}},css:function(a,b,d){var e,f=c.camelCase(b),h=c.cssHooks[f];b=c.cssProps[f]||f;if(h&&"get"in h&&(e=h.get(a,true,d))!==H)return e;else if(La)return La(a,
b,f)},swap:function(a,b,d){var e={};for(var f in b){e[f]=a.style[f];a.style[f]=b[f]}d.call(a);for(f in b)a.style[f]=e[f]},camelCase:function(a){return a.replace(jb,nb)}});c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(d,e,f){var h;if(e){if(d.offsetWidth!==0)h=W(d,b,f);else c.swap(d,mb,function(){h=W(d,b,f)});if(h<=0){h=La(d,b,b);if(h==="0px"&&Ma)h=Ma(d,b,b);if(h!=null)return h===""||h==="auto"?"0px":h}if(h<0||h==null){h=d.style[b];return h===""||h==="auto"?"0px":
h}return typeof h==="string"?h:h+"px"}},set:function(d,e){if(Za.test(e)){e=parseFloat(e);if(e>=0)return e+"px"}else return e}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return ib.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){a=a.style;a.zoom=1;b=c.isNaN(b)?"":"alpha(opacity="+b*100+")";var d=a.filter||"";a.filter=Ya.test(d)?d.replace(Ya,b):a.filter+" "+b}};if(z.defaultView&&z.defaultView.getComputedStyle)$a=
function(a,b,d){var e;d=d.replace(kb,"-$1").toLowerCase();if(!(b=a.ownerDocument.defaultView))return H;if(b=b.getComputedStyle(a,null)){e=b.getPropertyValue(d);if(e===""&&!c.contains(a.ownerDocument.documentElement,a))e=c.style(a,d)}return e};if(z.documentElement.currentStyle)Ma=function(a,b){var d,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;if(!Za.test(f)&&lb.test(f)){d=h.left;e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;h.left=b==="fontSize"?"1em":f||0;f=h.pixelLeft+"px";h.left=
d;a.runtimeStyle.left=e}return f===""?"auto":f};La=$a||Ma;if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style.display||c.css(a,"display"))==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var ob=c.now(),pb=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,qb=/^(?:select|textarea)/i,rb=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
sb=/^(?:GET|HEAD)$/,eb=/\[\]$/,Ca=/\=\?(&|$)/,Sa=/\?/,tb=/([?&])_=[^&]*/,ub=/^(\w+:)?\/\/([^\/?#]+)/,vb=/%20/g,wb=/#.*$/,ab=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&ab)return ab.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0){var f=a.slice(e,a.length);a=a.slice(0,e)}e="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);e="POST"}var h=this;c.ajax({url:a,type:e,dataType:"html",
data:b,complete:function(n,m){if(m==="success"||m==="notmodified")h.html(f?c("<div>").append(n.responseText.replace(pb,"")).find(f):n.responseText);d&&h.each(d,[n.responseText,m,n])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||qb.test(this.nodeName)||rb.test(this.type))}).map(function(a,b){a=c(this).val();
return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,e){if(c.isFunction(b)){e=e||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:e})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,
b,d,e){if(c.isFunction(b)){e=e||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:e})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:function(){return new T.XMLHttpRequest},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},
ajax:function(a){var b=c.extend(true,{},c.ajaxSettings,a),d,e,f,h=b.type.toUpperCase(),n=sb.test(h);b.url=b.url.replace(wb,"");b.context=a&&a.context!=null?a.context:b;if(b.data&&b.processData&&typeof b.data!=="string")b.data=c.param(b.data,b.traditional);if(b.dataType==="jsonp"){if(h==="GET")Ca.test(b.url)||(b.url+=(Sa.test(b.url)?"&":"?")+(b.jsonp||"callback")+"=?");else if(!b.data||!Ca.test(b.data))b.data=(b.data?b.data+"&":"")+(b.jsonp||"callback")+"=?";b.dataType="json"}if(b.dataType==="json"&&
(b.data&&Ca.test(b.data)||Ca.test(b.url))){d=b.jsonpCallback||"jsonp"+ob++;if(b.data)b.data=(b.data+"").replace(Ca,"="+d+"$1");b.url=b.url.replace(Ca,"="+d+"$1");b.dataType="script";var m=T[d];T[d]=function(r){if(c.isFunction(m))m(r);else{T[d]=H;try{delete T[d]}catch(t){}}f=r;c.handleSuccess(b,I,e,f);c.handleComplete(b,I,e,f);A&&A.removeChild(N)}}if(b.dataType==="script"&&b.cache===null)b.cache=false;if(b.cache===false&&n){var p=c.now(),G=b.url.replace(tb,"$1_="+p);b.url=G+(G===b.url?(Sa.test(b.url)?
"&":"?")+"_="+p:"")}if(b.data&&n)b.url+=(Sa.test(b.url)?"&":"?")+b.data;b.global&&c.active++===0&&c.event.trigger("ajaxStart");p=(p=ub.exec(b.url))&&(p[1]&&p[1].toLowerCase()!==location.protocol||p[2].toLowerCase()!==location.host);if(b.dataType==="script"&&h==="GET"&&p){var A=z.getElementsByTagName("head")[0]||z.documentElement,N=z.createElement("script");if(b.scriptCharset)N.charset=b.scriptCharset;N.src=b.url;if(!d){var R=false;N.onload=N.onreadystatechange=function(){if(!R&&(!this.readyState||
this.readyState==="loaded"||this.readyState==="complete")){R=true;c.handleSuccess(b,I,e,f);c.handleComplete(b,I,e,f);N.onload=N.onreadystatechange=null;A&&N.parentNode&&A.removeChild(N)}}}A.insertBefore(N,A.firstChild);return H}var fa=false,I=b.xhr();if(I){b.username?I.open(h,b.url,b.async,b.username,b.password):I.open(h,b.url,b.async);try{if(b.data!=null&&!n||a&&a.contentType)I.setRequestHeader("Content-Type",b.contentType);if(b.ifModified){c.lastModified[b.url]&&I.setRequestHeader("If-Modified-Since",
c.lastModified[b.url]);c.etag[b.url]&&I.setRequestHeader("If-None-Match",c.etag[b.url])}p||I.setRequestHeader("X-Requested-With","XMLHttpRequest");I.setRequestHeader("Accept",b.dataType&&b.accepts[b.dataType]?b.accepts[b.dataType]+", */*; q=0.01":b.accepts._default)}catch(ea){}if(b.beforeSend&&b.beforeSend.call(b.context,I,b)===false){b.global&&c.active--===1&&c.event.trigger("ajaxStop");I.abort();return false}b.global&&c.triggerGlobal(b,"ajaxSend",[I,b]);var oa=I.onreadystatechange=function(r){if(!I||
I.readyState===0||r==="abort"){fa||c.handleComplete(b,I,e,f);fa=true;if(I)I.onreadystatechange=c.noop}else if(!fa&&I&&(I.readyState===4||r==="timeout")){fa=true;I.onreadystatechange=c.noop;e=r==="timeout"?"timeout":!c.httpSuccess(I)?"error":b.ifModified&&c.httpNotModified(I,b.url)?"notmodified":"success";var t;if(e==="success")try{f=c.httpData(I,b.dataType,b)}catch(w){e="parsererror";t=w}if(e==="success"||e==="notmodified")d||c.handleSuccess(b,I,e,f);else c.handleError(b,I,e,t);d||c.handleComplete(b,
I,e,f);r==="timeout"&&I.abort();if(b.async)I=null}};try{var g=I.abort;I.abort=function(){I&&Function.prototype.call.call(g,I);oa("abort")}}catch(i){}b.async&&b.timeout>0&&setTimeout(function(){I&&!fa&&oa("timeout")},b.timeout);try{I.send(n||b.data==null?null:b.data)}catch(o){c.handleError(b,I,null,o);c.handleComplete(b,I,e,f)}b.async||oa();return I}},param:function(a,b){var d=[],e=function(h,n){n=c.isFunction(n)?n():n;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(n)};if(b===H)b=c.ajaxSettings.traditional;
if(c.isArray(a)||a.jquery)c.each(a,function(){e(this.name,this.value)});else for(var f in a)Y(f,a[f],b,e);return d.join("&").replace(vb,"+")}});c.extend({active:0,lastModified:{},etag:{},handleError:function(a,b,d,e){a.error&&a.error.call(a.context,b,d,e);a.global&&c.triggerGlobal(a,"ajaxError",[b,a,e])},handleSuccess:function(a,b,d,e){a.success&&a.success.call(a.context,e,d,b);a.global&&c.triggerGlobal(a,"ajaxSuccess",[b,a])},handleComplete:function(a,b,d){a.complete&&a.complete.call(a.context,b,
d);a.global&&c.triggerGlobal(a,"ajaxComplete",[b,a]);a.global&&c.active--===1&&c.event.trigger("ajaxStop")},triggerGlobal:function(a,b,d){(a.context&&a.context.url==null?c(a.context):c.event).trigger(b,d)},httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),e=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(e)c.etag[b]=
e;return a.status===304},httpData:function(a,b,d){var e=a.getResponseHeader("content-type")||"",f=b==="xml"||!b&&e.indexOf("xml")>=0;a=f?a.responseXML:a.responseText;f&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&e.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&e.indexOf("javascript")>=0)c.globalEval(a);return a}});if(T.ActiveXObject)c.ajaxSettings.xhr=function(){if(T.location.protocol!==
"file:")try{return new T.XMLHttpRequest}catch(a){}try{return new T.ActiveXObject("Microsoft.XMLHTTP")}catch(b){}};c.support.ajax=!!c.ajaxSettings.xhr();var Qa={},xb=/^(?:toggle|show|hide)$/,yb=/^([+\-]=)?([\d+.\-]+)(.*)$/,Na,Ta=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate(ja("show",3),a,b,d);else{d=0;for(var e=this.length;d<e;d++){a=
this[d];b=a.style.display;if(!c.data(a,"olddisplay")&&b==="none")b=a.style.display="";b===""&&c.css(a,"display")==="none"&&c.data(a,"olddisplay",ma(a.nodeName))}for(d=0;d<e;d++){a=this[d];b=a.style.display;if(b===""||b==="none")a.style.display=c.data(a,"olddisplay")||""}return this}},hide:function(a,b,d){if(a||a===0)return this.animate(ja("hide",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){d=c.css(this[a],"display");d!=="none"&&c.data(this[a],"olddisplay",d)}for(a=0;a<b;a++)this[a].style.display=
"none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||e?this.each(function(){var f=e?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(ja("toggle",3),a,b,d);return this},fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var f=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(f.complete);
return this[f.queue===false?"each":"queue"](function(){var h=c.extend({},f),n,m=this.nodeType===1,p=m&&c(this).is(":hidden"),G=this;for(n in a){var A=c.camelCase(n);if(n!==A){a[A]=a[n];delete a[n];n=A}if(a[n]==="hide"&&p||a[n]==="show"&&!p)return h.complete.call(this);if(m&&(n==="height"||n==="width")){h.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(c.css(this,"display")==="inline"&&c.css(this,"float")==="none")if(c.support.inlineBlockNeedsLayout)if(ma(this.nodeName)===
"inline")this.style.display="inline-block";else{this.style.display="inline";this.style.zoom=1}else this.style.display="inline-block"}if(c.isArray(a[n])){(h.specialEasing=h.specialEasing||{})[n]=a[n][1];a[n]=a[n][0]}}if(h.overflow!=null)this.style.overflow="hidden";h.curAnim=c.extend({},a);c.each(a,function(N,R){var fa=new c.fx(G,h,N);if(xb.test(R))fa[R==="toggle"?p?"show":"hide":R](a);else{var I=yb.exec(R),ea=fa.cur()||0;if(I){R=parseFloat(I[2]);var oa=I[3]||"px";if(oa!=="px"){c.style(G,N,(R||1)+
oa);ea=(R||1)/fa.cur()*ea;c.style(G,N,ea+oa)}if(I[1])R=(I[1]==="-="?-1:1)*R+ea;fa.custom(ea,R,oa)}else fa.custom(ea,R,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);this.each(function(){for(var e=d.length-1;e>=0;e--)if(d[e].elem===this){b&&d[e](true);d.splice(e,1)}});b||this.dequeue();return this}});c.each({slideDown:ja("show",1),slideUp:ja("hide",1),slideToggle:ja("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=
function(d,e,f){return this.animate(b,d,e,f)}});c.extend({speed:function(a,b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(){e.queue!==false&&c(this).dequeue();c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,d,e){return d+
e*a},swing:function(a,b,d,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a=parseFloat(c.css(this.elem,this.prop));return a&&a>-10000?
a:0},custom:function(a,b,d){function e(n){return f.step(n)}var f=this,h=c.fx;this.startTime=c.now();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;e.elem=this.elem;if(e()&&c.timers.push(e)&&!Na)Na=setInterval(h.tick,h.interval)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=
c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=c.now(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var e in this.options.curAnim)if(this.options.curAnim[e]!==true)d=false;if(d){if(this.options.overflow!=null&&!c.support.shrinkWrapBlocks){var f=this.elem,h=this.options;c.each(["","X","Y"],function(m,p){f.style["overflow"+p]=h.overflow[m]})}this.options.hide&&
c(this.elem).hide();if(this.options.hide||this.options.show)for(var n in this.options.curAnim)c.style(this.elem,n,this.options.orig[n]);this.options.complete.call(this.elem)}return false}else{a=b-this.startTime;this.state=a/this.options.duration;b=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||b](this.state,a,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};
c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(Na);Na=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=
function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var zb=/^t(?:able|d|h)$/i,bb=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in z.documentElement?function(a){var b=this[0],d;if(a)return this.each(function(n){c.offset.setOffset(this,a,n)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var f=b.ownerDocument,h=f.documentElement;if(!d||!c.contains(h,b))return d||{top:0,left:0};b=
f.body;f=va(f);return{top:d.top+(f.pageYOffset||c.support.boxModel&&h.scrollTop||b.scrollTop)-(h.clientTop||b.clientTop||0),left:d.left+(f.pageXOffset||c.support.boxModel&&h.scrollLeft||b.scrollLeft)-(h.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(A){c.offset.setOffset(this,a,A)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d,e=b.offsetParent,f=b,h=b.ownerDocument,n=h.documentElement,
m=h.body;d=(h=h.defaultView)?h.getComputedStyle(b,null):b.currentStyle;for(var p=b.offsetTop,G=b.offsetLeft;(b=b.parentNode)&&b!==m&&b!==n;){if(c.offset.supportsFixedPosition&&d.position==="fixed")break;d=h?h.getComputedStyle(b,null):b.currentStyle;p-=b.scrollTop;G-=b.scrollLeft;if(b===e){p+=b.offsetTop;G+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&zb.test(b.nodeName))){p+=parseFloat(d.borderTopWidth)||0;G+=parseFloat(d.borderLeftWidth)||0}f=e;e=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&
d.overflow!=="visible"){p+=parseFloat(d.borderTopWidth)||0;G+=parseFloat(d.borderLeftWidth)||0}d=d}if(d.position==="relative"||d.position==="static"){p+=m.offsetTop;G+=m.offsetLeft}if(c.offset.supportsFixedPosition&&d.position==="fixed"){p+=Math.max(n.scrollTop,m.scrollTop);G+=Math.max(n.scrollLeft,m.scrollLeft)}return{top:p,left:G}};c.offset={initialize:function(){var a=z.body,b=z.createElement("div"),d,e,f,h=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,
margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;f=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=e.offsetTop!==
5;this.doesAddBorderForTableAndCells=f.offsetTop===5;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=e.offsetTop===20||e.offsetTop===15;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=e.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==h;a.removeChild(b);c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=
parseFloat(c.css(a,"marginTop"))||0;d+=parseFloat(c.css(a,"marginLeft"))||0}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),h=f.offset(),n=c.css(a,"top"),m=c.css(a,"left"),p=e==="absolute"&&c.inArray("auto",[n,m])>-1;e={};var G={};if(p)G=f.position();n=p?G.top:parseInt(n,10)||0;m=p?G.left:parseInt(m,10)||0;if(c.isFunction(b))b=b.call(a,d,h);if(b.top!=null)e.top=b.top-h.top+n;if(b.left!=null)e.left=b.left-h.left+m;"using"in
b?b.using.call(a,e):f.css(e)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=bb.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||
z.body;a&&!bb.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(e){var f=this[0],h;if(!f)return null;if(e!==H)return this.each(function(){if(h=va(this))h.scrollTo(!a?e:c(h).scrollLeft(),a?e:c(h).scrollTop());else this[d]=e});else return(h=va(f))?"pageXOffset"in h?h[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&h.document.documentElement[d]||h.document.body[d]:f[d]}});c.each(["Height","Width"],
function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(e){return this[0]?parseFloat(c.css(this[0],d,e?"margin":"border")):null};c.fn[d]=function(e){var f=this[0];if(!f)return e==null?null:this;if(c.isFunction(e))return this.each(function(n){var m=c(this);m[d](e.call(this,n,m[d]()))});if(c.isWindow(f))return f.document.compatMode==="CSS1Compat"&&f.document.documentElement["client"+b]||f.document.body["client"+
b];else if(f.nodeType===9)return Math.max(f.documentElement["client"+b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]);else if(e===H){f=c.css(f,d);var h=parseFloat(f);return c.isNaN(h)?f:h}else return this.css(d,typeof e==="string"?e:e+"px")}});typeof define!=="undefined"&&define("jquery",[],function(){return c})})(window);
